# Generated by Django 2.0.4 on 2018-05-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(help_text='Enter User Name', max_length=20)),
                ('password', models.CharField(help_text='Enter a password', max_length=20)),
                ('first', models.CharField(help_text='Enter your first Name', max_length=20)),
                ('last', models.CharField(help_text='Enter your last name', max_length=20)),
                ('admin', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=True)),
                ('about_me', models.CharField(default='', max_length=100)),
                ('question1', models.IntegerField(default=0)),
                ('question2', models.IntegerField(default=0)),
                ('question3', models.IntegerField(default=0)),
                ('question4', models.IntegerField(default=0)),
                ('question5', models.IntegerField(default=0)),
                ('result1', models.CharField(default='', max_length=30)),
                ('result2', models.CharField(default='', max_length=30)),
                ('result3', models.CharField(default='', max_length=30)),
                ('result4', models.CharField(default='', max_length=30)),
                ('result5', models.CharField(default='', max_length=30)),
                ('result6', models.CharField(default='', max_length=30)),
                ('result7', models.CharField(default='', max_length=30)),
                ('result8', models.CharField(default='', max_length=30)),
                ('result9', models.CharField(default='', max_length=30)),
                ('result10', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
