# Generated by Django 2.0.4 on 2018-04-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='question1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='question2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='question3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='question4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='question5',
            field=models.IntegerField(default=0),
        ),
    ]
