# Generated by Django 2.0.4 on 2018-04-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180429_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='question6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='question7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='question8',
            field=models.IntegerField(default=0),
        ),
    ]
