# Generated by Django 2.0.4 on 2018-05-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20180429_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='/media/profile-placeholde.png', upload_to=''),
        ),
    ]
